electronic = [
    ['Portishead', 'Dummy', 'electronic'], 
    ['Aphex Twin', 'Selected Ambient Works 85-92', 'electronic'], 
    ['Daft Punk', 'Discovery', 'electronic'], 
    ['Massive Attack', 'Mezzanine', 'electronic'], 
    ['Boards of Canada', 'Music Has the Right to Children', 'electronic'], 
    ['Burial', 'Untrue', 'electronic'], 
    ['Boards of Canada', 'Geogaddi', 'electronic'], 
    ['Kraftwerk', 'Trans Europa Express', 'electronic'], 
    ['Coil', 'The Ape of Naples', 'electronic'], 
    ['Aphex Twin', 'Selected Ambient Works Volume II', 'electronic'], 
    ['Flying Lotus', 'Cosmogramma', 'electronic'], 
    ['Aphex Twin', 'Richard D. James Album', 'electronic'], 
    ['Aphex Twin', 'drukqs', 'electronic'], 
    ['Tim Hecker', 'Virgins', 'electronic'], 
    ['Coil', 'Musick to Play in the Dark', 'electronic'], 
    ['Lil Ugly Mane', 'Volcanic Bird Enemy and the Voiced Concern', 'electronic'], 
    ['Portishead', 'Portishead', 'electronic'], 
    ['Steve Roach', 'Structures From Silence', 'electronic'], 
    ['SOPHIE', 'OIL OF EVERY PEARL\'S UN-INSIDES', 'electronic'], 
    ['Brian Eno with Daniel Lanois & Roger Eno', 'Apollo: Atmospheres & Soundtracks', 'electronic'], 
    ['Ludwig van Beethoven', 'Clockwork Orange', 'electronic'], 
    ['Oneohtrix Point Never', 'Replica', 'electronic'], 
    ['Xiu Xiu', 'A Promise', 'electronic'], 
    ['Manuel Göttsching', 'E2-E4', 'electronic'], 
    ['Klaus Schulze', '"X"', 'electronic'], 
    ['Roland Kayn', 'Tektra', 'electronic'], 
    ['Autechre', 'Autechre [LP5]', 'electronic'], 
    ['Autechre', 'Confield', 'electronic'], 
    ['Coil', 'Black Antlers', 'electronic'], 
    ['SOPHIE', 'PRODUCT', 'electronic'], 
    ['Autechre', 'Tri repetae', 'electronic'], 
    ['DJ Sprinkles', 'Midtown 120 Blues', 'electronic'], 
    ['Against All Logic', '2012 - 2017', 'electronic'], 
    ['Eliane Radigue', 'Trilogie de la mort', 'electronic'], 
    ['Suicide', 'Suicide', 'electronic'], 
    ['Massive Attack', 'Blue Lines', 'electronic'], 
    ['Gaelle', 'Transient', 'electronic'], 
    ['Biosphere', 'Substrata', 'electronic'], 
    ['Coil', 'Musick to Play in the Dark²', 'electronic'], 
    ['Jon Hopkins', 'Immunity', 'electronic'], 
    ['Ιάννης Ξενάκης', 'Persepolis', 'electronic'], 
    ['death\'s dynamic shroud.wmv', 'I\'ll Try Living Like This', 'electronic'], 
    ['SOPHIE', 'Oil of Every Pearl\'s Un-Insides Remix Album (Non Stop)', 'electronic'], 
    ['Henri Pousseur', 'Paysages planétaires', 'electronic'], 
    ['Ryuichi Sakamoto', 'Thousand Knives of Ryuichi Sakamoto', 'electronic'], 
    ['Prodigy', 'The Fat of the Land', 'electronic'], 
    ['Klaus Schulze', 'Mirage', 'electronic'], 
    ['Boards of Canada', 'The Campfire Headphase', 'electronic'], 
    ['石川忠', 'Tetsuo', 'electronic'], 
    ['Tangerine Dream', 'Phaedra', 'electronic'], 
    ['Jean Michel Jarre', 'Oxygène', 'electronic'], 
    ['t e l e p a t h テレパシー能力者', '星間性交 (Seikan seikou)', 'electronic'], 
    ['Daft Punk', 'Random Access Memories', 'electronic'], 
    ['Oneohtrix Point Never', 'R Plus Seven', 'electronic'], 
    ['Todd Edwards', 'Prima edizione', 'electronic'], 
    ['Eliane Radigue', 'Kyema, Intermediate States', 'electronic'], 
    ['The Tuss', 'Rushup Edge', 'electronic'], 
    ['Venetian Snares', 'Rossz csillag alatt született', 'electronic'], 
    ['Эдуард Артемьев', 'Solaris, The Mirror, Stalker: Music From Motion Pictures', 'electronic'], 
    ['The Field', 'From Here We Go Sublime', 'electronic'], 
    ['Underworld', 'Dubnobasswithmyheadman', 'electronic'], 
    ['Ulver', 'Perdition City', 'electronic'], 
    ['The KLF', 'Chill Out', 'electronic'], 
    ['DJ Sabrina the Teenage DJ', 'Charmed', 'electronic'], 
    ['Kraftwerk', 'Autobahn', 'electronic'], 
    ['Maria & The Mirrors', 'Vision Quest', 'electronic'], 
    ['Orbital', 'Orbital [Brown Album]', 'electronic'], 
    ['Tangerine Dream', 'Rubycon', 'electronic'], 
    ['Tricky', 'Maxinquaye', 'electronic'], 
    ['Four Tet', 'Rounds', 'electronic'], 
    ['Klaus Schulze', 'Timewind', 'electronic'], 
    ['Steve Roach', 'Mystic Chords & Sacred Spaces', 'electronic'], 
    ['Ashra', 'New Age of Earth', 'electronic'], 
    ['Chuck Person', 'Chuck Person\'s Eccojams Vol. 1', 'electronic'], 
    ['2814', '新しい日の誕生 (Atarashī hi no tanjō)', 'electronic'], 
    ['Coil', 'Love\'s Secret Domain', 'electronic'], 
    ['Underworld', 'Second Toughest in the Infants', 'electronic'], 
    ['虚拟梦想广场', '无限渴望', 'electronic'], 
    ['Klaus Schulze', 'Moondawn', 'electronic'], 
    ['Ilkae', 'Pistachio Island', 'electronic'], 
    ['Terry Riley', 'A Rainbow in Curved Air', 'electronic'], 
    ['Christoph de Babalon', 'If You\'re Into It, I\'m Out of It', 'electronic'], 
    ['Amon Tobin', 'Permutation', 'electronic'], 
    ['Orbital', 'In Sides', 'electronic'], 
    ['Ιάννης Ξενάκης', 'Electro-Acoustic Music', 'electronic'], 
    ['Flying Lotus', 'Los Angeles', 'electronic'], 
    ['Broadcast', 'Tender Buttons', 'electronic'], 
    ['t e l e p a t h テレパシー能力者', '現実を超えて (Genjitsu o koete)', 'electronic'], 
    ['Michael Pisaro-Liu', 'Continuum Unbound', 'electronic'], 
    ['pilotredsun', 'Achievement', 'electronic'], 
    ['Bernard Parmegiani', 'De natura sonorum', 'electronic'], 
    ['Keith Rowe', 'Duos for Doris', 'electronic'], 
    ['Autechre', 'Amber', 'electronic'], 
    ['Jean Michel Jarre', 'Equinoxe', 'electronic'], 
    ['Sora', 're.sort', 'electronic'], 
    ['GAS', 'Königsforst', 'electronic'], 
    ['Autechre', 'elseq 4', 'electronic'], 
    ['Keith Rowe', 'The Room Extended', 'electronic'], 
    ['Wendy Carlos', 'Beauty in the Beast', 'electronic'], 
    ['虚拟梦想广场', '一见钟情', 'electronic'], 
    ['Oneohtrix Point Never', 'Garden of Delete', 'electronic'], 
    ['The Prodigy', 'Music for the Jilted Generation', 'electronic'], 
    ['GAS', 'Zauberberg', 'electronic'], 
    ['Depressive Silence', 'Depressive Silence II', 'electronic'], 
    ['Tangerine Dream', 'Zeit', 'electronic'], 
    ['DJ Sabrina the Teenage DJ', 'Makin\' Magick', 'electronic'], 
    ['Squarepusher', 'Feed Me Weird Things', 'electronic'], 
    ['Deepchord Presents Echospace', 'Liumin', 'electronic'], 
    ['Skee Mask', 'Compro', 'electronic'], 
    ['Prince of Denmark', '8', 'electronic'], 
    ['Jan Jelinek', 'Loop-finding-jazz-records', 'electronic'], 
    ['Nuno Canavarro', 'Plux Quba', 'electronic'], 
    ['Psykovsky', 'Da Budet', 'electronic'], 
    ['Squarepusher', 'Hard Normal Daddy', 'electronic'], 
    ['Amon Tobin', 'Supermodified', 'electronic'], 
    ['Handsomeboy Technique', 'Adelie Land', 'electronic'], 
    ['The Chemical Brothers', 'Dig Your Own Hole', 'electronic'], 
    ['Machine Girl', 'WLFGRL', 'electronic'], 
    ['Fennesz', 'Endless Summer', 'electronic']
]
