folk = [
    ['Nick Drake', 'Pink Moon', 'folk'], 
    ['The Microphones', 'The Glow Pt. 2', 'folk'], 
    ['Elliott Smith', 'Either / Or', 'folk'], 
    ['Leonard Cohen', 'Songs of Leonard Cohen', 'folk'], 
    ['Sufjan Stevens', 'Carrie & Lowell', 'folk'], 
    ['Joni Mitchell', 'Blue', 'folk'], 
    ['Nick Drake', 'Five Leaves Left', 'folk'], 
    ['Joanna Newsom', 'Ys', 'folk'], 
    ['Leonard Cohen', 'Songs of Love and Hate', 'folk'], 
    ['Comus', 'First Utterance', 'folk'], 
    ['The Microphones', 'Mount Eerie', 'folk'], 
    ['Townes Van Zandt', 'Townes Van Zandt', 'folk'], 
    ['Joanna Newsom', 'Have One on Me', 'folk'], 
    ['Van Morrison', 'Astral Weeks', 'folk'], 
    ['Bob Dylan', 'The Freewheelin\' Bob Dylan', 'folk'], 
    ['Nick Drake', 'Bryter Layter', 'folk'], 
    ['Mount Eerie', 'A Crow Looked at Me', 'folk'], 
    ['Elliott Smith', 'Elliott Smith', 'folk'], 
    ['青葉市子', '0', 'folk'], 
    ['Natural Snow Buildings', 'Daughter of Darkness', 'folk'], 
    ['Robbie Basho', 'Visions of the Country', 'folk'], 
    ['青葉市子', 'アダンの風 (Windswept Adan)', 'folk'], 
    ['Exuma', 'Exuma', 'folk'], 
    ['Natural Snow Buildings', 'The Dance of the Moon and the Sun', 'folk'], 
    ['The Microphones', 'Microphones in 2020', 'folk'], 
    ['John Fahey', 'Fare Forward Voyagers (Soldier\'s Choice)', 'folk'], 
    ['Fleet Foxes', 'Helplessness Blues', 'folk'], 
    ['Townes Van Zandt', 'Our Mother the Mountain', 'folk'], 
    ['Jackson C. Frank', 'Jackson C. Frank', 'folk'], 
    ['Joanna Newsom', 'Divers', 'folk'], 
    ['David Kauffman', 'Songs From Suicide Bridge', 'folk'], 
    ['Nico', 'Desertshore', 'folk'], 
    ['Bruce Springsteen', 'Nebraska', 'folk'], 
    ['Le Mystère des Voix Bulgares', 'Le mystère des voix bulgares : volume 1', 'folk'], 
    ['Lingua Ignota', 'Sinner Get Ready', 'folk'], 
    ['Bon Iver', 'For Emma, Forever Ago', 'folk'], 
    ['Milton Nascimento', 'Milagre dos peixes', 'folk'], 
    ['The Mountain Goats', 'All Hail West Texas', 'folk'], 
    ['高木正勝', 'かがやき (Kagayaki)', 'folk'], 
    ['Van Morrison', 'Veedon Fleece', 'folk'], 
    ['Sufjan Stevens', 'Michigan', 'folk'], 
    ['Milton Nascimento', 'Minas', 'folk'], 
    ['Fleet Foxes', 'Fleet Foxes', 'folk'], 
    ['The Mountain Goats', 'The Sunset Tree', 'folk'], 
    ['Harmonium', 'Les cinq saisons', 'folk'], 
    ['Roy Harper', 'Stormcock', 'folk'], 
    ['Milton Nascimento', 'Geraes', 'folk'], 
    ['John Fahey', 'Volume 6: Days Have Gone By', 'folk'], 
    ['Fabrizio De André', 'Storia di un impiegato', 'folk'], 
    ['John Fahey', 'America', 'folk'], 
    ['The Mountain Goats', 'Tallahassee', 'folk'], 
    ['Grouper', 'Dragging a Dead Deer Up a Hill', 'folk'], 
    ['Elliott Smith', 'Roman Candle', 'folk'], 
    ['Joanna Newsom', 'The Milk-Eyed Mender', 'folk'], 
    ['Tim Buckley', 'Happy Sad', 'folk'], 
    ['Nico', 'The Marble Index', 'folk'], 
    ['青葉市子', 'qp', 'folk'], 
    ['Joni Mitchell', 'Ladies of the Canyon', 'folk'], 
    ['Pastor T.L. Barrett', 'Like a Ship... (Without a Sail)', 'folk'], 
    ['Natural Snow Buildings', 'Shadow Kingdom', 'folk'], 
    ['Phoebe Bridgers', 'Punisher', 'folk'], 
    ['Leonard Cohen', 'New Skin for the Old Ceremony', 'folk'], 
    ['Fabrizio De André', 'La buona novella', 'folk'], 
    ['John Prine', 'John Prine', 'folk'], 
    ['Lula Côrtes', 'Paêbirú', 'folk'], 
    ['Bob Dylan', 'The Times They Are A-Changin\'', 'folk'], 
    ['Son House', 'Father of Folk Blues', 'folk'], 
    ['John Fahey', 'Vol. II: Death Chants, Breakdowns and Military Waltzes', 'folk'], 
    ['Zé Ramalho', 'A peleja do Diabo com o dono do céu', 'folk'], 
    ['戸張大輔', 'ドラム (Drum)', 'folk'], 
    ['Nature and Organisation', 'Beauty Reaps the Blood of Solitude', 'folk'], 
    ['Current 93', 'Thunder Perfect Mind', 'folk'], 
    ['Linda Perhacs', 'Parallelograms', 'folk'], 
    ['Mississippi John Hurt', 'Today!', 'folk'], 
    ['Jim O\'Rourke', 'Bad Timing', 'folk'], 
    ['Adrianne Lenker', 'Songs', 'folk'], 
    ['Zé Ramalho', 'Zé Ramalho', 'folk'], 
    ['Tim Buckley', 'Lorca', 'folk'], 
    ['Mount Eerie', 'Dawn: Winter Journal', 'folk'], 
    ['Fabrizio De André', 'Tutti morimmo a stento', 'folk'], 
    ['Sun Kil Moon', 'Benji', 'folk'], 
    ['Vashti Bunyan', 'Just Another Diamond Day', 'folk'], 
    ['Sufjan Stevens', 'A Beginner\'s Mind', 'folk'], 
    ['Muddy Waters', 'Folk Singer', 'folk'], 
    ['Milton Nascimento', 'Clube da Esquina 2', 'folk'], 
    ['Judee Sill', 'Heart Food', 'folk'], 
    ['Current Ninety Three', 'Sleep Has His House', 'folk'], 
    ['Elizabeth Cotten', 'Folksongs and Instrumentals With Guitar', 'folk'], 
    ['Fafá de Belém', 'Água', 'folk'], 
    ['Judee Sill', 'Judee Sill', 'folk'], 
    ['Martinho da Vila', 'Canta canta minha gente', 'folk'], 
    ['Lankum', 'False Lankum', 'folk'], 
    ['Mississippi Fred McDowell', 'I Do Not Play No Rock \'n\' Roll', 'folk'], 
    ['Current 93', 'Of Ruine or Some Blazing Starre', 'folk'], 
    ['Sufjan Stevens', 'Seven Swans', 'folk'], 
    ['Junior Kimbrough', 'Most Things Haven\'t Worked Out', 'folk'], 
    ['The Nitty Gritty Dirt Band', 'Will the Circle Be Unbroken', 'folk'], 
    ['Fabrizio De André', 'Crêuza de mä', 'folk'], 
    ['John Fahey', 'The Yellow Princess', 'folk'], 
    ['Doc Watson', 'Memories', 'folk'], 
    ['Leonard Cohen', 'Songs From a Room', 'folk'], 
    ['Current 93', 'All the Pretty Little Horses', 'folk'], 
    ['Beverly Glenn-Copeland', 'Beverly Glenn-Copeland', 'folk'], 
    ['José Afonso', 'Cantigas do Maio', 'folk'], 
    ['青葉市子', '剃刀乙女 (Kamisori otome)', 'folk'], 
    ['Gillian Welch', 'Time (The Revelator)', 'folk'], 
    ['Johnny Cash', 'American Recordings', 'folk'], 
    ['Leo Kottke', '6- & 12-String Guitar', 'folk'], 
    ['Natalia Lafourcade', 'Un canto por México vol. 1', 'folk'], 
    ['Fabrizio De André', 'Anime salve', 'folk'], 
    ['Daniel Johnston', 'Hi, How Are You: The Unfinished Album', 'folk'], 
    ['Andy Irvine', 'Andy Irvine & Paul Brady', 'folk'], 
    ['Animal Collective', 'Sung Tongs', 'folk'], 
    ['Księżyc', 'Księżyc', 'folk'], 
    ['The Mountain Goats', 'We Shall All Be Healed', 'folk'], 
    ['森田童子', 'A Boy ボーイ', 'folk'], 
    ['Fausto', 'Por este rio acima', 'folk'], 
    ['Beto Guedes', 'A página do relâmpago elétrico', 'folk'], 
    ['Mississippi John Hurt', 'Last Sessions', 'folk'], 
    ['Mount Eerie', 'Lost Wisdom', 'folk']
]
