jazz = [
    ['Mingus', 'The Black Saint and the Sinner Lady', 'jazz'], 
    ['John Coltrane', 'A Love Supreme', 'jazz'], 
    ['Miles Davis', 'Kind of Blue', 'jazz'], 
    ['Miles Davis', 'In a Silent Way', 'jazz'], 
    ['Miles Davis', 'Bitches Brew', 'jazz'], 
    ['Pharoah Sanders', 'Karma', 'jazz'], 
    ['John Coltrane', 'Giant Steps', 'jazz'], 
    ['John Coltrane', 'My Favorite Things', 'jazz'], 
    ['Charles Mingus', 'Mingus Ah Um', 'jazz'], 
    ['Alice Coltrane featuring Pharoah Sanders', 'Journey in Satchidananda', 'jazz'], 
    ['Art Blakey and The Jazz Messengers', 'Art Blakey and The Jazz Messengers [Moanin\']', 'jazz'], 
    ['Miles Davis', 'Get Up With It', 'jazz'], 
    ['John Coltrane', 'Blue Train', 'jazz'], 
    ['Charlie Mingus', 'Blues & Roots', 'jazz'], 
    ['Herbie Hancock', 'Head Hunters', 'jazz'], 
    ['Charles Mingus', 'Let My Children Hear Music', 'jazz'], 
    ['Nina Simone', 'Pastel Blues', 'jazz'], 
    ['Stan Getz & João Gilberto', 'Getz / Gilberto', 'jazz'], 
    ['John Coltrane', 'Ascension [Edition I]', 'jazz'], 
    ['Ornette Coleman', 'The Shape of Jazz to Come', 'jazz'], 
    ['Sun Ra', 'Lanquidity', 'jazz'], 
    ['Eric Dolphy', 'Out to Lunch', 'jazz'], 
    ['The John Coltrane Quartet', 'Africa / Brass', 'jazz'], 
    ['John Coltrane', 'Olé Coltrane', 'jazz'], 
    ['The Dave Brubeck Quartet', 'Time Out', 'jazz'], 
    ['Pharoah Sanders', 'Black Unity', 'jazz'], 
    ['Miles Davis', 'On the Corner', 'jazz'], 
    ['Charles Mingus', 'Mingus Mingus Mingus Mingus Mingus', 'jazz'], 
    ['Sonny Rollins', 'Saxophone Colossus', 'jazz'], 
    ['Art Blakey & The Jazz Messengers', 'Free for All', 'jazz'], 
    ['Nina Simone', 'Wild Is the Wind', 'jazz'], 
    ['Cannonball Adderley', 'Somethin\' Else', 'jazz'], 
    ['Komeda Quintet', 'Astigmatic', 'jazz'], 
    ['The Horace Silver Quintet', 'Song for My Father (Cantiga para meu pai)', 'jazz'], 
    ['渋さ知らズ', '渋星 (Shibuboshi)', 'jazz'], 
    ['Sun Ra and His Arkestra', 'Sleeping Beauty', 'jazz'], 
    ['Herbie Hancock', 'Sextant', 'jazz'], 
    ['Pharoah Sanders', 'Love in Us All', 'jazz'], 
    ['John Coltrane', 'Meditations', 'jazz'], 
    ['Duke Ellington', 'Duke Ellington\'s Far East Suite', 'jazz'], 
    ['Wayne Shorter', 'Speak No Evil', 'jazz'], 
    ['Art Blakey & The Jazz Messengers', 'Mosaic', 'jazz'], 
    ['Floating Points', 'Promises', 'jazz'], 
    ['John Coltrane', 'Sun Ship', 'jazz'], 
    ['Pharoah Sanders', 'Deaf Dumb Blind (Summun bukmun umyun)', 'jazz'], 
    ['Sonny Sharrock', 'Ask the Ages', 'jazz'], 
    ['Don Cherry', 'Don Cherry', 'jazz'], 
    ['Herbie Hancock', 'Empyrean Isles', 'jazz'], 
    ['Thelonious Monk Septet', 'Monk\'s Music', 'jazz'], 
    ['The Sonny Criss Orchestra', 'Sonny\'s Dream (Birth of the New Cool)', 'jazz'], 
    ['Grant Green', 'Idle Moments', 'jazz'], 
    ['Lee Morgan', 'Search for the New Land', 'jazz'], 
    ['Miles Davis', 'Sketches of Spain', 'jazz'], 
    ['The Thelonious Monk Quartet', 'Monk\'s Dream', 'jazz'], 
    ['The Cannonball Adderley Quintet', 'Mercy, Mercy, Mercy!', 'jazz'], 
    ['John Coltrane', 'Ascension [Edition II]', 'jazz'], 
    ['Alice Coltrane', 'Ptah, the El Daoud', 'jazz'], 
    ['Max Roach', 'We Insist! Max Roach\'s Freedom Now Suite', 'jazz'], 
    ['Lee Morgan', 'The Sidewinder', 'jazz'], 
    ['McCoy Tyner', 'The Real McCoy', 'jazz'], 
    ['The Ornette Coleman Double Quartet', 'Free Jazz', 'jazz'], 
    ['Duke Ellington', 'Money Jungle', 'jazz'], 
    ['Ornette Coleman', 'Science Fiction', 'jazz'], 
    ['Thelonious Monk', 'Straight, No Chaser', 'jazz'], 
    ['Herbie Hancock', 'Maiden Voyage', 'jazz'], 
    ['Matana Roberts', 'Coin Coin Chapter One: Gens de couleur libres', 'jazz'], 
    ['Anthony Braxton', 'Willisau (Quartet) 1991', 'jazz'], 
    ['The Jazz Composer\'s Orchestra', 'The Jazz Composer\'s Orchestra', 'jazz'], 
    ['Wayne Shorter', 'Juju', 'jazz'], 
    ['Nina Simone', 'Little Girl Blue', 'jazz'], 
    ['Oliver Nelson', 'The Blues and the Abstract Truth', 'jazz'], 
    ['John Coltrane Quartet', 'Crescent', 'jazz'], 
    ['McCoy Tyner', 'Sahara', 'jazz'], 
    ['Thelonious Monk', 'Brilliant Corners', 'jazz'], 
    ['Clifford Brown & Max Roach', 'Clifford Brown and Max Roach', 'jazz'], 
    ['Andrew Hill', 'Point of Departure', 'jazz'], 
    ['Grachan Moncur III', 'Evolution', 'jazz'], 
    ['Miles Davis Quintet', 'Miles Smiles', 'jazz'], 
    ['Max Roach and His Chorus and Orchestra', 'It\'s Time', 'jazz'], 
    ['Wayne Shorter', 'Adam\'s Apple', 'jazz'], 
    ['Miles Davis', '\'Round About Midnight', 'jazz'], 
    ['Andrew Hill', 'Compulsion', 'jazz'], 
    ['Pete La Roca', 'Basra', 'jazz'], 
    ['Miles Davis', 'Milestones', 'jazz'], 
    ['Dexter Gordon', 'One Flight Up', 'jazz'], 
    ['The Peter Brötzmann Octet', 'Machine Gun', 'jazz'], 
    ['The Charlie Mingus Jazz Workshop', 'Pithecanthropus erectus', 'jazz'], 
    ['Clifford Brown & Max Roach', 'Study in Brown', 'jazz'], 
    ['Bill Evans', 'You Must Believe in Spring', 'jazz'], 
    ['Yusef Lateef', 'Eastern Sounds', 'jazz'], 
    ['Dizzy Gillespie', 'Sonny Side Up', 'jazz'], 
    ['Jackie McLean', 'Destination Out!', 'jazz'], 
    ['Sonny Sharrock', 'Black Woman', 'jazz'], 
    ['Art Ensemble of Chicago', 'Les stances à Sophie', 'jazz'], 
    ['Art Blakey & The Jazz Messengers', 'A Night in Tunisia', 'jazz'], 
    ['Joe Henderson featuring Alice Coltrane', 'The Elements', 'jazz'], 
    ['Miles Davis', 'Nefertiti', 'jazz'], 
    ['David Holland Quartet', 'Conference of the Birds', 'jazz'], 
    ['Art Blakey & The Jazz Messengers', 'Indestructible', 'jazz'], 
    ['Charlie Mingus', 'Tijuana Moods', 'jazz'], 
    ['Miles Davis', 'Panthalassa: The Music of Miles Davis 1969-1974', 'jazz'], 
    ['Gil Scott-Heron & Brian Jackson', 'Bridges', 'jazz'], 
    ['Roland Kirk', 'The Inflated Tear', 'jazz'], 
    ['Lee Morgan', 'Lee Morgan', 'jazz'], 
    ['The Roland Kirk Quartet', 'Rip, Rig and Panic', 'jazz'], 
    ['Joe Henderson', 'Mode for Joe', 'jazz'], 
    ['Pedro Iturralde', '¡Jazz Flamenco!', 'jazz'], 
    ['Albert Ayler Trio', 'Spiritual Unity', 'jazz'], 
    ['Miles Davis', 'Big Fun', 'jazz'], 
    ['Duke Ellington', 'The Afro-Eurasian Eclipse', 'jazz'], 
    ['Joe Henderson', 'Inner Urge', 'jazz'], 
    ['Eric Dolphy', 'Out There', 'jazz'], 
    ['Pharoah Sanders', 'Thembi', 'jazz'], 
    ['Hank Mobley', 'Soul Station', 'jazz'], 
    ['Sonny Clark', 'Cool Struttin\'', 'jazz'], 
    ['Freddie Hubbard', 'Straight Life', 'jazz'], 
    ['Andrew Hill', 'Black Fire', 'jazz'], 
    ['Pharoah Sanders', 'Izipho Zam (My Gifts)', 'jazz'], 
    ['Tomasz Stanko Quintet', 'Purple Sun', 'jazz'], 
    ['Wes Montgomery', 'The Incredible Jazz Guitar of Wes Montgomery', 'jazz']
]