pop  = [
    ['The Beach Boys', 'Pet Sounds', 'pop'], 
    ['Kate Bush', 'Hounds of Love', 'pop'], 
    ['Frank Ocean', 'Blonde', 'pop'], 
    ['Sufjan Stevens', 'Illinois', 'pop'], 
    ['The Zombies', 'Odessey and Oracle', 'pop'], 
    ['Kate Bush', 'The Dreaming', 'pop'], 
    ['Michael Jackson', 'Thriller', 'pop'], 
    ['Weyes Blood', 'Titanic Rising', 'pop'], 
    ['Elliott Smith', 'XO', 'pop'], 
    ['The Flaming Lips', 'The Soft Bulletin', 'pop'], 
    ['Scott Engel', 'Scott 4', 'pop'], 
    ['Fiona Apple', 'The Idler Wheel Is Wiser Than the Driver of the Screw and Whipping Cords Will Serve You More Than Ropes Will Ever Do', 'pop'], 
    ['Frank Ocean', 'Endless', 'pop'], 
    ['The Flaming Lips', 'Yoshimi Battles the Pink Robots', 'pop'], 
    ['Animal Collective', 'Strawberry Jam', 'pop'], 
    ['Michael Jackson', 'Off the Wall', 'pop'], 
    ['Talk Talk', 'The Colour of Spring', 'pop'], 
    ['Kate Bush', 'Never for Ever', 'pop'], 
    ['Jessie Ware', 'What\'s Your Pleasure?', 'pop'], 
    ['Gal Costa', 'Gal Costa', 'pop'], 
    ['Lamp', '恋人へ (Koibito e)', 'pop'], 
    ['Elliott Smith', 'Figure 8', 'pop'], 
    ['The Magnetic Fields', '69 Love Songs', 'pop'], 
    ['Sade', 'Promise', 'pop'], 
    ['山下達郎', 'Ride on Time', 'pop'], 
    ['Arthur Verocai', 'Arthur Verocai', 'pop'], 
    ['Janelle Monáe', 'The ArchAndroid', 'pop'], 
    ['Scott Walker', 'Scott 3', 'pop'], 
    ['Joni Mitchell', 'The Hissing of Summer Lawns', 'pop'], 
    ['Amy Winehouse', 'Back to Black', 'pop'], 
    ['Lana Del Rey', 'Norman Fucking Rockwell!', 'pop'], 
    ['Fiona Apple', 'Fetch the Bolt Cutters', 'pop'], 
    ['Panda Bear', 'Person Pitch', 'pop'], 
    ['Lucio Battisti', 'Anima latina', 'pop'], 
    ['Serge Gainsbourg', 'Histoire de Melody Nelson', 'pop'], 
    ['Sade', 'Diamond Life', 'pop'], 
    ['Julia Holter', 'Have You in My Wilderness', 'pop'], 
    ['Dusty Springfield', 'Dusty in Memphis', 'pop'], 
    ['John Cale', 'Paris 1919', 'pop'], 
    ['Stereolab', 'Cobra and Phases Group Play Voltage in the Milky Night', 'pop'], 
    ['Ecco2k', 'E', 'pop'], 
    ['The Blue Nile', 'Hats', 'pop'], 
    ['山下達郎', 'For You', 'pop'], 
    ['The Millennium', 'Begin', 'pop'], 
    ['Brian Wilson', 'Smile', 'pop'], 
    ['Jim O\'Rourke', 'Eureka', 'pop'], 
    ['Minnie Riperton', 'Come to My Garden', 'pop'], 
    ['Weyes Blood', 'And in the Darkness, Hearts Aglow', 'pop'], 
    ['The Ronettes', 'Presenting The Fabulous Ronettes Featuring Veronica', 'pop'], 
    ['Kate Bush', 'The Sensual World', 'pop'], 
    ['Tindersticks', 'Tindersticks [II]', 'pop'], 
    ['XTC', 'Apple Venus Volume 1', 'pop'], 
    ['Café Tacvba', 'Re', 'pop'], 
    ['David Sylvian', 'Secrets of the Beehive', 'pop'], 
    ['Tindersticks', 'Tindersticks', 'pop'], 
    ['杏里', 'Timely!!', 'pop'], 
    ['Tori Amos', 'From the Choirgirl Hotel', 'pop'], 
    ['Janet Jackson', 'Rhythm Nation 1814', 'pop'], 
    ['平沢進', 'Sim City', 'pop'], 
    ['平沢進', 'Aurora', 'pop'], 
    ['Destroyer', 'Kaputt', 'pop'], 
    ['Joan Manuel Serrat', 'Mediterráneo', 'pop'], 
    ['Prefab Sprout', 'Jordan: The Comeback', 'pop'], 
    ['Julia Holter', 'Loud City Song', 'pop'], 
    ['Julia Holter', 'Aviary', 'pop'], 
    ['Minnie Riperton', 'Adventures in Paradise', 'pop'], 
    ['Sam Cooke', 'Ain\'t That Good News', 'pop'], 
    ['Laura Nyro', 'Eli and the Thirteenth Confession', 'pop'], 
    ['"Blue" Gene Tyranny', 'Out of the Blue', 'pop'], 
    ['Björk', 'Vulnicura', 'pop'], 
    ['Frédéric Chopin', 'Doopee Time', 'pop'], 
    ['Sparks', 'Lil\' Beethoven', 'pop'], 
    ['Dean Blunt', 'Black Metal', 'pop'], 
    ['Lamp', '東京ユウトピア通信 (Tokyo Utopia Tsushin)', 'pop'], 
    ['Vampire Weekend', 'Modern Vampires of the City', 'pop'], 
    ['David Sylvian', 'Brilliant Trees', 'pop'], 
    ['Stereolab', 'Sound-Dust', 'pop'], 
    ['Issam Hajali', 'Mouasalat ila jacad el ard', 'pop'], 
    ['SPELLLING', 'The Turning Wheel', 'pop'], 
    ['The Left Banke', 'Walk Away Renée / Pretty Ballerina', 'pop'], 
    ['Electrocutica', 'Piece of Cipher +', 'pop'], 
    ['Lamp', 'ゆめ (Yume)', 'pop'], 
    ['The Magnetic Fields', 'Get Lost', 'pop'], 
    ['Tindersticks', 'Curtains', 'pop'], 
    ['Ferkat al Ard', 'أغنية (Oghneya)', 'pop'], 
    ['Richard Hawley', 'Truelove\'s Gutter', 'pop'], 
    ['Japanese Breakfast', 'Jubilee', 'pop'], 
    ['Frank Sinatra', 'Watertown', 'pop'], 
    ['矢野顕子', 'ごはんができたよ (Gohan ga dekitayo)', 'pop'], 
    ['The Olivia Tremor Control', 'Black Foliage: Animation Music Volume 1', 'pop'], 
    ['Gilberto Gil', 'Gilberto Gil', 'pop'], 
    ['The Supremes', 'Where Did Our Love Go', 'pop'], 
    ['The Unicorns', 'Who Will Cut Our Hair When We\'re Gone?', 'pop'], 
    ['Tori Amos', 'Boys for Pele', 'pop'], 
    ['Lalleshwari', 'Lullabies in a Glass Wilderness', 'pop'], 
    ['平沢進', '賢者のプロペラ (Kenja no Propeller)', 'pop'], 
    ['Jens Lekman', 'Night Falls Over Kortedala', 'pop'], 
    ['Elvis Presley', 'From Elvis in Memphis', 'pop'], 
    ['Kate Bush', 'Aerial', 'pop'], 
    ['Four Tops', 'Reach Out', 'pop'], 
    ['きくお', 'きくおミク6 (Kikuo Miku 6)', 'pop'], 
    ['Teleradio Donoso', 'Bailar y llorar', 'pop'], 
    ['角松敏生', 'After 5 Clash', 'pop'], 
    ['Nancy Sinatra & Lee Hazlewood', 'Nancy & Lee', 'pop'], 
    ['Serani Poji', 'One-Room Survival', 'pop'], 
    ['The Olivia Tremor Control', 'Music From the Unrealized Film Script, Dusk at Cubist Castle', 'pop'], 
    ['Janet Jackson', 'Control', 'pop'], 
    ['Bill Fay', 'Bill Fay', 'pop'], 
    ['Marek Grechuta', 'Marek Grechuta & Anawa', 'pop'], 
    ['El Niño Gusano', 'El escarabajo más grande de Europa', 'pop'], 
    ['きくおはな', '第二幕 (Dai-ni-maku)', 'pop'], 
    ['The Blue Nile', 'A Walk Across the Rooftops', 'pop'], 
    ['Sugar Babe', 'Songs', 'pop'], 
    ['きくおはな', '第一幕 (Dai-ichi-maku)', 'pop'], 
    ['Nilsson', 'Aerial Ballet', 'pop'], 
    ['Janet Jackson', 'Janet.', 'pop'], 
    ['Laura Nyro', 'New York Tendaberry', 'pop'], 
    ['Michael Jackson', 'Bad', 'pop'], 
    ['Tori Amos', 'Under the Pink', 'pop']
]