rock = [
    ['Radiohead', 'OK Computer', 'rock'], 
    ['Pink Floyd', 'Wish You Were Here', 'rock'], 
    ['King Crimson', 'In the Court of the Crimson King', 'rock'], 
    ['My Bloody Valentine', 'Loveless', 'rock'], 
    ['Radiohead', 'In Rainbows', 'rock'], 
    ['Pink Floyd', 'The Dark Side of the Moon', 'rock'], 
    ['Talking Heads', 'Remain in Light', 'rock'], 
    ['The Velvet Underground', 'The Velvet Underground & Nico', 'rock'], 
    ['Godspeed You Black Emperor!', 'Lift Yr. Skinny Fists Like Antennas to Heaven!', 'rock'], 
    ['Black Sabbath', 'Paranoid', 'rock'], 
    ['The Cure', 'Disintegration', 'rock'], 
    ['King Crimson', 'Red', 'rock'], 
    ['Slint', 'Spiderland', 'rock'], 
    ['Pink Floyd', 'Animals', 'rock'], 
    ['Joy Division', 'Unknown Pleasures', 'rock'], 
    ['Godspeed You Black Emperor!', 'F♯A♯∞', 'rock'], 
    ['Slowdive', 'Souvlaki', 'rock'], 
    ['Bob Dylan', 'Highway 61 Revisited', 'rock'], 
    ['David Bowie', 'Low', 'rock'], 
    ['Pixies', 'Doolittle', 'rock'], 
    ['Television', 'Marquee Moon', 'rock'], 
    ['Yes', 'Close to the Edge', 'rock'], 
    ['Cocteau Twins', 'Heaven or Las Vegas', 'rock'], 
    ['Led Zeppelin', 'Led Zeppelin [IV]', 'rock'], 
    ['Bob Dylan', 'Blonde on Blonde', 'rock'], 
    ['David Bowie', 'Blackstar', 'rock'], 
    ['Black Sabbath', 'Master of Reality', 'rock'], 
    ['The Jimi Hendrix Experience', 'Electric Ladyland', 'rock'], 
    ['Swans', 'Soundtracks for the Blind', 'rock'], 
    ['The Doors', 'The Doors', 'rock'], 
    ['Bob Dylan', 'Blood on the Tracks', 'rock'], 
    ['Joy Division', 'Closer', 'rock'], 
    ['Talk Talk', 'Laughing Stock', 'rock'], 
    ['David Bowie', 'Station to Station', 'rock'], 
    ['The Jimi Hendrix Experience', 'Are You Experienced', 'rock'], 
    ['Metallica', 'Ride the Lightning', 'rock'], 
    ['Have a Nice Life', 'Deathconsciousness', 'rock'], 
    ['Can', 'Future Days', 'rock'], 
    ['Black Sabbath', 'Black Sabbath', 'rock'], 
    ['Sonic Youth', 'Daydream Nation', 'rock'], 
    ['Can', 'Tago Mago', 'rock'], 
    ['Nine Inch Nails', 'The Downward Spiral', 'rock'], 
    ['Death', 'Symbolic', 'rock'], 
    ['Sigur Rós', 'Ágætis byrjun', 'rock'], 
    ['Nirvana', 'Nevermind', 'rock'], 
    ['Metallica', 'Master of Puppets', 'rock'], 
    ['Nirvana', 'In Utero', 'rock'], 
    ['Modest Mouse', 'The Lonesome Crowded West', 'rock'], 
    ['Talk Talk', 'Spirit of Eden', 'rock'], 
    ['Neil Young', 'After the Gold Rush', 'rock'], 
    ['The Stooges', 'Fun House', 'rock'], 
    ['Tom Waits', 'Rain Dogs', 'rock'], 
    ['The Clash', 'London Calling', 'rock'], 
    ['The Cure', 'Pornography', 'rock'], 
    ['The Velvet Underground', 'White Light / White Heat', 'rock'], 
    ['Swans', 'To Be Kind', 'rock'], 
    ['Neil Young', 'On the Beach', 'rock'], 
    ['The Strokes', 'Is This It', 'rock'], 
    ['Jeff Buckley', 'Grace', 'rock'], 
    ['Eno', 'Another Green World', 'rock'], 
    ['Megadeth', 'Rust in Peace', 'rock'], 
    ['King Crimson', 'Larks\' Tongues in Aspic', 'rock'], 
    ['Built to Spill', 'Perfect From Now On', 'rock'], 
    ['Can', 'Ege Bamyası', 'rock'], 
    ['Unwound', 'Leaves Turn Inside You', 'rock'], 
    ['Neil Young', 'Everybody Knows This Is Nowhere', 'rock'], 
    ['Pink Floyd', 'Meddle', 'rock'], 
    ['Talking Heads', 'Fear of Music', 'rock'], 
    ['David Bowie', '"Heroes"', 'rock'], 
    ['Interpol', 'Turn on the Bright Lights', 'rock'], 
    ['Iggy and The Stooges', 'Raw Power', 'rock'], 
    ['Smashing Pumpkins', 'Siamese Dream', 'rock'], 
    ['Rage Against the Machine', 'Rage Against the Machine', 'rock'], 
    ['Genesis', 'Selling England by the Pound', 'rock'], 
    ['Car Seat Headrest', 'Twin Fantasy', 'rock'], 
    ['Creedence Clearwater Revival', 'Cosmo\'s Factory', 'rock'], 
    ['The Rolling Stones', 'Sticky Fingers', 'rock'], 
    ['Judas Priest', 'Painkiller', 'rock'], 
    ['Iron Maiden', 'Powerslave', 'rock'], 
    ['Electric Wizard', 'Dopethrone', 'rock'], 
    ['Magnolia Electric Co.', 'The Magnolia Electric Co.', 'rock'], 
    ['Duster', 'Stratosphere', 'rock'], 
    ['The Stone Roses', 'The Stone Roses', 'rock'], 
    ['Queens of the Stone Age', 'Songs for the Deaf', 'rock'], 
    ['Tool', 'Lateralus', 'rock'], 
    ['Led Zeppelin', 'Led Zeppelin', 'rock'], 
    ['King Crimson', 'Discipline', 'rock'], 
    ['Jethro Tull', 'Thick as a Brick', 'rock'], 
    ['Slayer', 'Reign in Blood', 'rock'], 
    ['Neil Young', 'Harvest', 'rock'], 
    ['Boris', 'Boris at Last -Feedbacker-', 'rock'], 
    ['Boris', 'Flood', 'rock'], 
    ['Cocteau Twins', 'Treasure', 'rock'], 
    ['Swans', 'The Seer', 'rock'], 
    ['Converge', 'Jane Doe', 'rock'], 
    ['Alice in Chains', 'Dirt', 'rock'], 
    ['Radiohead', 'The Bends', 'rock'], 
    ['Black Sabbath', 'Sabbath Bloody Sabbath', 'rock'], 
    ['Deftones', 'White Pony', 'rock'], 
    ['Pavement', 'Crooked Rain, Crooked Rain', 'rock'], 
    ['Death', 'Human', 'rock'], 
    ['Dead Kennedys', 'Fresh Fruit for Rotting Vegetables', 'rock'], 
    ['Invisible', 'El jardín de los presentes', 'rock'], 
    ['Led Zeppelin', 'Led Zeppelin II', 'rock'], 
    ['Funkadelic', 'Maggot Brain', 'rock'], 
    ['Wilco', 'Yankee Hotel Foxtrot', 'rock'], 
    ['black midi', 'Hellfire', 'rock'], 
    ['The Rolling Stones', 'Exile on Main St.', 'rock'], 
    ['Pixies', 'Surfer Rosa', 'rock'], 
    ['Ween', 'Quebec', 'rock'], 
    ['Led Zeppelin', 'Physical Graffiti', 'rock'], 
    ['Opeth', 'Blackwater Park', 'rock'], 
    ['The Jimi Hendrix Experience', 'Axis: Bold as Love', 'rock'], 
    ['Gang of Four', 'Entertainment!', 'rock'], 
    ['Modest Mouse', 'The Moon & Antarctica', 'rock'], 
    ['Iron Maiden', 'Seventh Son of a Seventh Son', 'rock'], 
    ['The Rolling Stones', 'Let It Bleed', 'rock'], 
    ['Yes', 'Fragile', 'rock'], 
    ['Tom Waits', 'Swordfishtrombones', 'rock'], 
    ['At the Drive-In', 'Relationship of Command', 'rock'], 
]